cargo-features = ["codegen-backend"]

[package]
name = "v_exchanges_api_generics"
version = "0.3.1"
edition = "2024"

authors = ["negi_grass", "valeratrades"]
categories = ["api-bindings", "asynchronous"]
description = "A client for HTTP/HTTPS/WebSocket APIs."
documentation = "https://docs.rs/v_exchanges_api_generics"
homepage = "https://github.com/valeratrades/v_exchanges"
keywords = ["client", "websocket", "asynchronous"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/valeratrades/v_exchanges/tree/master/v_exchanges_api_generics"

[dependencies]
bytes = "1.9.0"
parking_lot = "0.12.3"
tokio-tungstenite = "0.26.0"

futures-util.workspace = true
reqwest.workspace = true
v_utils.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
native-tls = ["reqwest/native-tls", "tokio-tungstenite/native-tls"]
native-tls-vendored = ["reqwest/native-tls-vendored", "tokio-tungstenite/native-tls-vendored"]
rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots", "tokio-tungstenite/rustls-tls-native-roots"]
rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots"]
