env:
  CARGO_INCREMENTAL: '0'
  CARGO_NET_RETRY: '10'
  RUSTUP_MAX_RETRIES: '10'
  RUST_BACKTRACE: short
jobs:
  env:
    CARGO_INCREMENTAL: '0'
    CARGO_NET_RETRY: '10'
    RUSTUP_MAX_RETRIES: '10'
    RUST_BACKTRACE: short
  if: needs.pre_ci.outputs.continue
  jobs:
    pre_ci:
      uses: valeratrades/.github/.github/workflows/pre_ci.yml@master
  name: Miri
  needs: pre_ci
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - uses: dtolnay/rust-toolchain@miri
  - name: Download modified by pre-ci Cargo.toml files
    uses: actions/download-artifact@v4
    with:
      name: modified-cargo-files
  - run: cargo miri setup
  - env:
      MIRIFLAGS: -Zmiri-strict-provenance
    run: cargo miri test
  timeout-minutes: 45
name: Errors
'on':
  pull_request: {}
  push: {}
  workflow_dispatch: {}
permissions:
  contents: read
