jobs:
  env:
    CARGO_INCREMENTAL: '0'
    CARGO_NET_RETRY: '10'
    RUSTDOCFLAGS: -Dwarnings
    RUSTUP_MAX_RETRIES: '10'
    RUST_BACKTRACE: short
  if: github.event_name != 'pull_request'
  jobs:
    pre_ci:
      uses: valeratrades/.github/.github/workflows/pre_ci.yml@master
  name: Reasonable Amount of Comments
  needs: pre_ci
  runs-on: ubuntu-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
  - name: Installation
    uses: taiki-e/install-action@v2
    with:
      tool: tokei
  - name: Generate Tokei output
    run: tokei -o json > tokei_output.json
  - name: Install jq
    run: sudo apt-get install -y jq
  - name: Check Rust comments
    run: "\t\t\t\t\t\tcomments=$(jq '.Rust.comments' tokei_output.json)\n\t\t\t\t\t\
      \tcode=$(jq '.Rust.code' tokei_output.json)\n\t\t\t\t\t\tif [ $((comments *\
      \ 10)) -ge $code ]; then\n\t\t\t\t\t\t\techo \"Number of comments should be\
      \ less than 10% of code\"\n\t\t\t\t\t\t\texit 1\n\t\t\t\t\t\telse\n\t\t\t\t\t\
      \t\techo \"Check passed: Number of comments is less than 10% of code\"\n\t\t\
      \t\t\t\tfi\n\t\t\t"
  timeout-minutes: 45
name: Warnings
'on':
  pull_request: {}
  push: {}
  workflow_dispatch: {}
permissions:
  contents: read
